# Generated by Django 5.0.14 on 2026-05-12 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('waktu_pelaksanaan', models.CharField(max_length=255)),
                ('pelaksana', models.CharField(max_length=255)),
                ('selesai', models.BooleanField(default=False)),
                ('evaluasi', models.TextField(blank=True, null=True)),
                ('rencana_tambahan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aktivitas',
                'verbose_name_plural': 'Aktivitas',
                'db_table': 'aktivitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('lokasi', models.CharField(max_length=255)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('pelaksana', models.CharField(max_length=255)),
                ('pengawas', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('engineering', 'Engineering'), ('creation', 'Creation'), ('implementation', 'Implementation')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pekerjaan',
                'verbose_name_plural': 'Pekerjaan',
                'db_table': 'pekerjaan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nim', models.CharField(max_length=20, unique=True, verbose_name='NIM')),
                ('name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='BuktiAktivitas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='bukti_aktivitas/%Y/%m/%d/')),
                ('ukuran_file', models.IntegerField(blank=True, null=True)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('aktivitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bukti', to='api.aktivitas')),
            ],
            options={
                'verbose_name': 'Bukti Aktivitas',
                'verbose_name_plural': 'Bukti Aktivitas',
                'db_table': 'bukti_aktivitas',
                'ordering': ['-diunggah_pada'],
            },
        ),
        migrations.AddField(
            model_name='aktivitas',
            name='pekerjaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas', to='api.pekerjaan'),
        ),
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('lokasi', models.CharField(max_length=255)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('pelaksana', models.CharField(max_length=255)),
                ('pengawas', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Selesai', 'Selesai'), ('Tertunda', 'Tertunda')], default='Aktif', max_length=20)),
                ('sudah_selesai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyek', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyek',
                'verbose_name_plural': 'Proyek',
                'db_table': 'proyek',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pekerjaan',
            name='proyek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pekerjaan', to='api.proyek'),
        ),
    ]
