# Generated by Django 5.0.14 on 2026-05-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerjaan',
            name='kategori',
            field=models.CharField(choices=[('teknik', 'Intelligence Engineering'), ('kreasi', 'Intelligence Creation'), ('implementasi', 'Implementation')], max_length=20),
        ),
    ]
