# Generated by Django 5.0.14 on 2026-05-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pekerjaan_kategori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nama',
        ),
    ]
