# Generated by Django 5.0.14 on 2026-05-14 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_user_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyek', to=settings.AUTH_USER_MODEL),
        ),
    ]
