# Generated by Django 5.0.14 on 2026-05-31 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_proyek_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pekerjaan',
            name='kategori',
        ),
    ]
