# Generated by Django 5.0.14 on 2026-06-04 23:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_pekerjaan_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('engineers', 'Engineers'), ('creation', 'Creation'), ('implementation', 'Implementation')], default='engineers', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/%d/')),
                ('submitted_by', models.CharField(max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pekerjaan',
            name='kategori',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('creation', 'Creation'), ('implementation', 'Implementation')], default='engineering', max_length=20),
        ),
    ]
