# Generated by Django 5.0.14 on 2026-06-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tasksubmission_pekerjaan_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='category',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('creation', 'Creation'), ('implementation', 'Implementation')], default='engineering', max_length=50),
        ),
    ]
